heat_template_version: 2014-10-16

description: >
  This is a nested stack that defines a single Kubernetes minion, This stack is
  included by an AutoScalingGroup resource in the parent template
  (kubecluster.yaml).

parameters:

  server_image:
    type: string
    description: glance image used to boot the server

  minion_flavor:
    type: string
    description: flavor to use when booting the server

  ssh_key_name:
    type: string
    description: name of ssh key to be provisioned on our server

  external_network:
    type: string
    description: uuid/name of a network to use for floating ip addresses

  fixed_network:
    type: string
    description: Network from which to allocate fixed addresses.

  kube_software_configs:
    type: string
    description : >
      ID of the multipart mime.

resources:

  ######################################################################
  #
  # a single kubernetes minion.
  #

  # do NOT use "_" (underscore) in the Nova server name
  # it creates a mismatch between the generated Nova name and its hostname
  # which can lead to weird problems
  kube-minion:
    type: OS::Nova::Server
    properties:
      image: {get_param: server_image}
      flavor: {get_param: minion_flavor}
      key_name: {get_param: ssh_key_name}
      user_data_format: RAW
      user_data: {get_param: kube_software_configs}
      networks:
        - network: {get_param: fixed_network}

  kube_minion_floating:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network:
        get_param: external_network
      port_id:
        get_attr: [kube-minion, addresses, {get_param: fixed_network}, 0, port]

outputs:

  kube_minion_ip:
    value: {get_attr: [kube-minion, networks, private, 0]}
    description: >
      This is the "public" IP address of the Kubernetes minion node.

  kube_minion_external_ip:
    value: {get_attr: [kube_minion_floating, floating_ip_address]}
    description: >
      This is the "public" IP address of the Kubernetes minion node.

  OS::stack_id:
    value: {get_param: "OS::stack_id"}
    description: >
      This is a id of the stack which creates from this template.
